### ISSUE TITLE
Koreander templates are not rendered via SpringBoot and fat JARs

### ISSUE THREAD

**Issue by Flameborn** [lukasjapan/koreander#5]
I am currently using Spring 5 and Koreander as the template engine. I am unfortunately getting a *java.lang.ArrayIndexOutOfBoundsException: Index 10912 out of bounds for length 10912]* error, at *de.cvguy.kotlin.koreander.Koreander.compile(Koreander.kt:62) ~[koreander-0.1-WIP.jar:na]*.

I am using a fat JAR, which requires the Kotlin compiler to be unpacked at startup, via:

`bootJar {
	requiresUnpack '**/kotlin-compiler-*.jar'
}`

My Spring application looks like:

`@SpringBootApplication
class TestApplication {
	@Bean fun koreanderViewResolver(): ViewResolver = KoreanderViewResolver()
}`

And the corresponding controller:

`
@Controller
class DemoController {
	@GetMapping("/demo")
	fun demo(): String {
		return "example"
	}
}`

I'm using *compile "de.cvguy.kotlin:koreander-spring:0.+"* via Gradle.

**Comment by lukasjapan** [comment]
Hi, thanks for using Koreander.

I saw this error before and it was due to a version mismatch of some kind. It has been fixed in recent package versions.

According to the log, you are using the `0.1-WIP` version of Koreander, my first attempt of release. Unfortunately I got the version naming wrong, so gradle probably mistook it as the latest version when specifying `0.+`.

I just deleted `0.1-WIP` from bintray, so re-resolving all dependencies should fix the issue. Alternatively you can try to specify `0.0.6` to be sure, I don't know how much caching takes place.

**Comment by Flameborn** [comment]
Thank you very much for the exceptionally quick reply.

Indeed, Koreander-Spring does not pull in Koreander 0.0.6, but the issue is resolved after an explicit dependency in *build.gradle*.

The template is unfortunately still not rendered, I am getting a *cannot access script base class* error when sending a GET request to a controller.

While I would appreciate a fix for this, in case you had something like this pop up in the past, I realize that this might be outside of the scope of Koreander, thus I consider this issue fixed. Thank you very much!
